db.brand.insert({"name":"杰士邦", "brand_id":1, "country_flag":0, "image":"jissbon.png"})
db.brand.insert({"name":"杜蕾斯", "brand_id":2, "country_flag":1, "image":"durex.png" })
db.brand.insert({"name":"倍力乐", "brand_id":3, "country_flag":0, "image":"pleasure.png"})
db.brand.insert({"name":"多乐士", "brand_id":4, "country_flag":0, "image":"donless.png"})
db.brand.insert({"name":"冈本", "brand_id":5, "country_flag":1, "image":"okamoto.png"})
db.brand.insert({"name":"第六感", "brand_id":6, "country_flag":1, "image":"sixsex.png"})
db.brand.insert({"name":"男子汉", "brand_id":7, "country_flag":0, "image":"strongman.png"})
db.brand.insert({"name":"冰果", "brand_id":8, "country_flag":1, "image":"bingoo.png"})
db.brand.insert({"name":"顽皮套套", "brand_id":9, "country_flag":0, "image":"wanpi.png"})
db.brand.insert({"name":"高邦", "brand_id":10, "country_flag":0, "image":"gobon.png"})

db.brand.ensureIndex({"name":1})